
import {
  CalendarDays,
  MessageCircle,
  UserRound,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";

const API_URL = "http://localhost:5000/api/bookings";


export default function Booking({ selectedDesign = "" }) {

    const videoRef = useRef(null);

useEffect(() => {
  const video = videoRef.current;

  if (!video) return;

  const observer = new IntersectionObserver(
    ([entry]) => {
      if (entry.isIntersecting) {
        video.play().catch(() => {});
      } else {
        video.pause();
      }
    },
    {
      threshold: 0.25,
    }
  );

  observer.observe(video);

  return () => {
    observer.disconnect();
  };
}, []);

  const [form, setForm] = useState({
    name: "",
    phone: "",
    date: "",
    design: selectedDesign,
    message: "",
  });

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  function handleChange(event) {
    const { name, value } = event.target;

    setForm((previous) => ({
      ...previous,
      [name]: value,
    }));
  }

  async function handleSubmit(event) {
    event.preventDefault();

    setLoading(true);
    setError("");

    try {
      const bookingData = {
        customerName: form.name,
        phone: form.phone,
        eventDate: form.date,
        eventType: "Other",
        design: form.design,
        location: "To be confirmed",
        guestCount: 1,
        message: form.message,
      };

      const response = await fetch(API_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(bookingData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.message || "Booking submission failed"
        );
      }

      alert("Booking saved successfully! 🌸");

      // Open WhatsApp link generated by backend
      if (data.whatsappUrl) {
        window.open(
          data.whatsappUrl,
          "_blank",
          "noopener,noreferrer"
        );
      }

      // Reset form
      setForm({
        name: "",
        phone: "",
        date: "",
        design: selectedDesign,
        message: "",
      });
    } catch (error) {
      console.error("Booking error:", error);
      setError(error.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <section id="contact" className="bg-cream">
      <div className="container-shell grid items-center gap-10 lg:grid-cols-2">
        {/* Left Content */}
        <div className="py-16 lg:py-24">
          <p className="eyebrow">
            Let's create something beautiful
          </p>

          <h2 className="display-title text-5xl">
            Book Your <em>Date</em>
          </h2>

          <p className="my-6 text-sm leading-7 text-[#746b61]">
            Tell us your requirements and send your enquiry
            directly through WhatsApp.
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Name */}
            <div>
              <label className="mb-1 block text-xs text-[#746b61]">
                Your Name
              </label>

              <div className="flex items-center gap-2 border-b border-[#b8aa99] py-2">
                <UserRound
                  size={15}
                  className="text-[#746b61]"
                />

                <input
                  type="text"
                  name="name"
                  value={form.name}
                  onChange={handleChange}
                  placeholder="Enter your name"
                  required
                  className="w-full bg-transparent text-sm outline-none placeholder:text-[#a99d90]"
                />
              </div>
            </div>

            {/* Phone */}
            <div>
              <label className="mb-1 block text-xs text-[#746b61]">
                Phone Number
              </label>

              <input
                type="tel"
                name="phone"
                value={form.phone}
                onChange={handleChange}
                placeholder="Enter your phone number"
                required
                className="w-full border-b border-[#b8aa99] bg-transparent py-2 text-sm outline-none placeholder:text-[#a99d90]"
              />
            </div>

            {/* Date */}
            <div>
              <label className="mb-1 block text-xs text-[#746b61]">
                Preferred Date
              </label>

              <div className="flex items-center gap-2 border-b border-[#b8aa99] py-2">
                <CalendarDays
                  size={15}
                  className="text-[#746b61]"
                />

                <input
                  type="date"
                  name="date"
                  value={form.date}
                  onChange={handleChange}
                  min={new Date().toISOString().split("T")[0]}
                  required
                  className="w-full bg-transparent text-sm outline-none"
                />
              </div>
            </div>

            {/* Selected Design */}
            <div>
              <label className="mb-1 block text-xs text-[#746b61]">
                Selected Design
              </label>

              <input
                type="text"
                name="design"
                value={form.design}
                onChange={handleChange}
                placeholder="e.g. Arabic, Bridal, Minimal"
                className="w-full border-b border-[#b8aa99] bg-transparent py-2 text-sm outline-none placeholder:text-[#a99d90]"
              />
            </div>

            {/* Message */}
            <div>
              <label className="mb-1 block text-xs text-[#746b61]">
                Additional Message
              </label>

              <textarea
                name="message"
                value={form.message}
                onChange={handleChange}
                placeholder="Tell us about your requirements..."
                rows={3}
                className="w-full resize-none border-b border-[#b8aa99] bg-transparent py-2 text-sm outline-none placeholder:text-[#a99d90]"
              />
            </div>

            {/* Error */}
            {error && (
              <p className="text-sm text-red-600">
                {error}
              </p>
            )}

            {/* Submit */}
            <button
              type="submit"
              disabled={loading}
              className="primary-button disabled:cursor-not-allowed disabled:opacity-60"
            >
              <MessageCircle size={15} />

              {loading
                ? "Submitting..."
                : "Send Enquiry on WhatsApp ↗"}
            </button>
          </form>
        </div>

        {/* Premium Mehendi Video */}
        <div className="relative mx-auto w-full max-w-xl p-3 sm:p-4">
          {/* Outer Decorative Border */}
          <div className="absolute inset-0 rounded-[220px_220px_24px_24px] border border-[#c9a77b]/60" />

          {/* Inner Video Frame */}
          <div className="relative overflow-hidden rounded-[200px_200px_16px_16px] border-4 border-[#efe2cf] bg-[#d8c4aa] p-1 shadow-[0_20px_60px_rgba(74,52,35,0.20)]">
            <video
            ref={videoRef}
              src="/showcase/footer-video.mp4"
              
              muted
              loop
              playsInline
              preload="metadata"
              aria-label="Mehendi being applied on a hand"
              className="h-[410px] w-full rounded-[190px_190px_12px_12px] object-cover saturate-[.75] transition duration-700 hover:scale-[1.02] sm:h-[520px]"
            />

            {/* Soft Overlay */}
            <div className="pointer-events-none absolute inset-1 rounded-[190px_190px_12px_12px] bg-gradient-to-t from-[#30452d]/15 via-transparent to-[#fffaf3]/10" />
          </div>

          {/* Decorative Corner */}
          <div className="absolute bottom-0 right-0 h-16 w-16 rounded-tl-full border-l border-t border-[#c9a77b]/50" />
        </div>
      </div>
    </section>
  );
}